---
deployment:
  tasks:
    - export DEPLOYPATH=/home/bizprope/public_html/
    - /bin/rsync -av
        --exclude='.git'
        --exclude='.gitignore'
        --exclude='.cpanel.yml'
        --exclude='.vercel'
        --exclude='vercel.json'
        ./ $DEPLOYPATH
